# Generated by Django 6.1.2 on 2026-10-06 17:34

import django.db.models.deletion
import salons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(db_index=True, help_text='e.g. Ruiru, Kileleshwa', max_length=100)),
                ('landmark', models.CharField(blank=True, help_text='e.g. Opposite Thika Road Mall', max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, help_text='Format: 2547XXXXXXXX', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Knotless braids (medium)', max_length=120)),
                ('category', models.CharField(choices=[('braids', 'Braids'), ('twists', 'Twists'), ('weaves', 'Weaves & weave-ons'), ('wigs', 'Wigs & installs'), ('natural', 'Natural hair care'), ('relaxer', 'Relaxers & treatments'), ('cuts', 'Cuts & styling'), ('other', 'Other')], default='other', max_length=10)),
                ('price_kes', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=salons.models.portfolio_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='salons.salon')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='salons.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
